[package]
name = "rust-magicq"
version = "0.1.0"
edition = "2021"

[lib]
name = "magicq"

# This specifies the executable crate type
[[bin]]
name = "magicq-generator"
path = "src/main.rs"

[dependencies]
itertools = "0.10.5"
nom = "7.1.3"
testsgenerator = { path = "tests/testsgenerator" }